name: ModernEnchants
version: @version@
main: me.jishuna.modernenchants.ModernEnchants
authors: [Jishuna]
depend: [ProtocolLib]
api-version: 1.17

commands:
  modernenchants:
    description: Base plugin command